### ISSUE TITLE
pacs pull interactive table mismatch

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/chrisreloaded#107]
# PACS pull interactive table reports wrong file numbers under certain situations.

## Overview
This is what it seems to me -- data shown in the full table is different to data shown on a filter.

To replicate:

1. Do a pacs_pull on 2253596;
2. Toggle to "Study" view;
3. Expand the second study:
3a. Note that for "SMS2-DTI 3 Shell b3000" the number of files is reported as 176;
3b. Note that for "WIPmocoMEMPRAGE 1mm FOV 256 RMS" the number of files is reported as 125;

Now:
4. Toggle to Series view;
5. Choose "All" in the DropDown "Show results";
6. Filter on WIP:
6a. Note that now "WIPmocoMEMPRAGE 1mm FOV 26 RMS" is reporting 176 files.
7. Filter on "DTI":
7a. Note that now "SMS2-DTI 3Shell b3000" is shown with 70 files.

**Comment by NicolasRannou** [comment]
Closed by https://github.com/FNNDSC/chrisreloaded/commit/bbc549fd07a24ccf13aa90420647e387bd79d5e4
